#!/bin/bash
set -x
FLAGS=""
if [ "$#" -gt 0 ]; then
    for n in "$@"
    do
        . <(sed -n $(($n+9))p $0)
    done
else
java -jar libs/kawa.jar $FLAGS -f src/test-parser.scm #1
java -jar libs/kawa.jar $FLAGS -f src/test-painter.scm #2
java -jar libs/kawa.jar $FLAGS -f src/test-editor-operations.scm #3
java -jar libs/kawa.jar $FLAGS -f src/test-document-operations.scm #4
java -jar libs/kawa.jar $FLAGS -f src/test-stepper.scm #5
java -jar libs/kawa.jar $FLAGS -f src/test-regressions.scm #6
fi
