;; Note: this file was generated from the ~grasp.org~
;; document, which also serves as the project's documentation.
;; 
;; Please do not edit this file directly, as all the changes
;; will be overwritten after code regeneration.

(module-name (editor architecture))
(import (language extensions))

(define-interface Interactive ()
  ;; by convention, the function that reacted to the input
  ;; ought to return #true
  (tap! finger::byte #;at x::real y::real)::boolean
  (press! finger::byte #;at x::real y::real)::boolean
  (second-press! finger::byte #;at x::real y::real)::boolean
  (double-tap! finger::byte x::real y::real)::boolean
  (long-press! finger::byte x::real y::real)::boolean
  (key-typed! key-code::long)::boolean)

(define-interface Drag ()
  (move! x::real y::real dx::real dy::real)::void
  (drop! x::real y::real vx::real vy::real)::void
  )

(define-interface Visual ()
  (render! active? ::boolean)::void)

(define-interface Tile ()
  (width)::real
  (height)::real)

(define-interface ResizableTile (Tile)
  (min-width)::real
  (min-height)::real
  (set-size! new-width::real new-height::real anchor::(maybe Object))::void)

(define-interface Application (Interactive Visual ResizableTile))

(define-interface Tile ()
  (width)::real
  (height)::real)

(define-interface KeyboardNavigable ()
  ;; likewise, the above functions should return #true
  ;; only if the cursor has actually been moved
  (move-cursor-left!)::boolean
  (move-cursor-right!)::boolean
  (move-cursor-up!)::boolean
  (move-cursor-down!)::boolean)

(define-interface Undoable ()
  (undo!)::boolean
  (redo!)::boolean)

#|
(define-interface Selectable ()
  (expand-selection-left!)::boolean
  (expand-selection-right!)::boolean
  (expand-selection-up!)::boolean
  (expand-selection-down!)::boolean)
|#
