;; Note: this file was generated from the ~grasp.org~
;; document, which also serves as the project's documentation.
;; 
;; Please do not edit this file directly, as all the changes
;; will be overwritten after code regeneration, and modify
;; the ~grasp.org~ file instead.

(module-name (editor architecture))
(import (language extensions))

(define-interface CanManageCoordinateSystem ()
  (with-translation x::real y::real acion::(maps () to: ,A))::,A
  (with-rotation angle::real action::(maps () to: ,A))::,A
  (with-clip w::real h::real action::(maps () to: ,A))::,A
  (with-intensity intensity::<0.0-1.0> action::(maps () to: ,A)::,A
  (with-stretch horizontal::real vertical::real action::(maps () to: ,A))::,A
  )

(define-interface CanRenderBoxes ()
  )

(define-interface Painter (
CanManageCoordinateSystem
CanRenderBoxes
))

(define-object (NullPainter)::Painter
  ;; CanManageCoordinateSystem
  (define (with-translation x::real y::real acion::(maps () to: ,A))::,A
    (action))
  
  (define (with-rotation angle::real action::(maps () to: ,A))::,A
    (action))
  
  (define (with-clip w::real h::real action::(maps () to: ,A))::,A
    (action))
  
  (define (with-intensity intensity::<0.0-1.0> action::(maps () to: ,A))::,A
    (action))
  
  (define (with-stretch horizontal::real vertical::real action::(maps () to: ,A))::,A
    (action))
  
  ;; CanRenderBoxes
  
)
