;; Note: this file was generated from the ~grasp.org~
;; document, which also serves as the project's documentation.
;; 
;; Please do not edit this file directly, as all the changes
;; will be overwritten after code regeneration, and modify
;; the ~grasp.org~ file instead.

(module-name (editor text-painter))
