(import (input))
(define-alias KeyEvent android.view.KeyEvent)

(define (initialize-keymap)

  (set! (key-code-name KeyEvent:KEYCODE_F1) 'F1)
  (set! (key-code-name KeyEvent:KEYCODE_F2) 'F2)
  (set! (key-code-name KeyEvent:KEYCODE_F3) 'F3)
  (set! (key-code-name KeyEvent:KEYCODE_F4) 'F4)
  (set! (key-code-name KeyEvent:KEYCODE_F5) 'F5)
  (set! (key-code-name KeyEvent:KEYCODE_F6) 'F6)
  (set! (key-code-name KeyEvent:KEYCODE_F7) 'F7)
  (set! (key-code-name KeyEvent:KEYCODE_F8) 'F8)
  (set! (key-code-name KeyEvent:KEYCODE_F9) 'F9)
  (set! (key-code-name KeyEvent:KEYCODE_F10) 'F10)
  (set! (key-code-name KeyEvent:KEYCODE_F11) 'F11)
  (set! (key-code-name KeyEvent:KEYCODE_F12) 'F12)

  (set! (key-code-name KeyEvent:KEYCODE_0) 0)
  (set! (key-code-name KeyEvent:KEYCODE_1) 1)
  (set! (key-code-name KeyEvent:KEYCODE_2) 2)
  (set! (key-code-name KeyEvent:KEYCODE_3) 3)
  (set! (key-code-name KeyEvent:KEYCODE_4) 4)
  (set! (key-code-name KeyEvent:KEYCODE_5) 5)
  (set! (key-code-name KeyEvent:KEYCODE_6) 6)
  (set! (key-code-name KeyEvent:KEYCODE_7) 7)
  (set! (key-code-name KeyEvent:KEYCODE_8) 8)
  (set! (key-code-name KeyEvent:KEYCODE_9) 9)

  (set! (key-code-name KeyEvent:KEYCODE_A) 'a)
  (set! (key-code-name KeyEvent:KEYCODE_B) 'b)
  (set! (key-code-name KeyEvent:KEYCODE_C) 'c)
  (set! (key-code-name KeyEvent:KEYCODE_D) 'd)
  (set! (key-code-name KeyEvent:KEYCODE_E) 'e)
  (set! (key-code-name KeyEvent:KEYCODE_F) 'f)
  (set! (key-code-name KeyEvent:KEYCODE_G) 'g)
  (set! (key-code-name KeyEvent:KEYCODE_H) 'h)
  (set! (key-code-name KeyEvent:KEYCODE_I) 'i)
  (set! (key-code-name KeyEvent:KEYCODE_J) 'j)
  (set! (key-code-name KeyEvent:KEYCODE_K) 'k)
  (set! (key-code-name KeyEvent:KEYCODE_L) 'l)
  (set! (key-code-name KeyEvent:KEYCODE_M) 'm)
  (set! (key-code-name KeyEvent:KEYCODE_N) 'n)
  (set! (key-code-name KeyEvent:KEYCODE_O) 'o)
  (set! (key-code-name KeyEvent:KEYCODE_P) 'p)
  (set! (key-code-name KeyEvent:KEYCODE_Q) 'q)
  (set! (key-code-name KeyEvent:KEYCODE_R) 'r)
  (set! (key-code-name KeyEvent:KEYCODE_S) 's)
  (set! (key-code-name KeyEvent:KEYCODE_T) 't)
  (set! (key-code-name KeyEvent:KEYCODE_U) 'u)
  (set! (key-code-name KeyEvent:KEYCODE_V) 'v)
  (set! (key-code-name KeyEvent:KEYCODE_W) 'w)
  (set! (key-code-name KeyEvent:KEYCODE_X) 'x)
  (set! (key-code-name KeyEvent:KEYCODE_Y) 'y)
  (set! (key-code-name KeyEvent:KEYCODE_Z) 'z)

  (set! (key-code-name KeyEvent:KEYCODE_DPAD_LEFT) 'left)
  (set! (key-code-name KeyEvent:KEYCODE_DPAD_RIGHT) 'right)
  (set! (key-code-name KeyEvent:KEYCODE_DPAD_UP) 'up)
  (set! (key-code-name KeyEvent:KEYCODE_DPAD_DOWN) 'down)
  
  (set! (key-code-name KeyEvent:KEYCODE_DPAD_CENTER) 'center)
  (set! (key-code-name KeyEvent:KEYCODE_DPAD_UP_LEFT) 'up-left)
  (set! (key-code-name KeyEvent:KEYCODE_DPAD_UP_RIGHT) 'up-right)
  (set! (key-code-name KeyEvent:KEYCODE_DPAD_DOWN_LEFT) 'down-left)
  (set! (key-code-name KeyEvent:KEYCODE_DPAD_DOWN_RIGHT) 'down-right)

  (set! (key-code-name KeyEvent:KEYCODE_SPACE) 'space)
  (set! (key-code-name KeyEvent:KEYCODE_DEL) 'backspace)
  (set! (key-code-name KeyEvent:KEYCODE_FORWARD_DEL) 'delete)

  (set! (key-code-name KeyEvent:KEYCODE_ENTER) 'enter)

  
  )

